import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import styled from 'styled-components';

const Heading = styled.h1`
  margin-bottom: 48px;
  font-size: 64px;
`;
const Button  = styled.button`
  font-size: 16px;
  padding: 12px 24px;
  background: #010101;
  border: none;
  color: white;
  font-weight: 500;
  margin-right: 32px;
  border-radius: 4px;
  cursor: pointer;
`;
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading>Resume Builder</Heading>
        <Link href="/edit">
          <Button>Edit</Button>
        </Link>
        <Link href="/preview">
          <Button>Preview</Button>
        </Link>
      </main>
    </div>
  )
}
